// This file is generated by the discover-tests script

#include "rs-core/unit-test.hpp"
#include <print>
#include <string>
#include <vector>

using namespace RS::UnitTest;

void test_rs_graphics_colour_space_concepts();
void test_rs_graphics_colour_space_ciexyy();
void test_rs_graphics_colour_space_cielab();
void test_rs_graphics_colour_space_cieluv();
void test_rs_graphics_colour_space_hclab();
void test_rs_graphics_colour_space_hcluv();
void test_rs_graphics_colour_space_srgb();
void test_rs_graphics_colour_space_adobe_rgb();
void test_rs_graphics_colour_space_pro_photo();
void test_rs_graphics_colour_space_wide_gamut();
void test_rs_graphics_colour_space_hsl();
void test_rs_graphics_colour_space_hsv();
void test_rs_graphics_colour_space_greyscale();
void test_rs_graphics_colour_space_sgreyscale();
void test_rs_graphics_colour_space_conversion();
void test_rs_graphics_colour_floating_point_elements();
void test_rs_graphics_colour_floating_point_arithmetic();
void test_rs_graphics_colour_floating_point_standard_colours();
void test_rs_graphics_colour_integral_elements();
void test_rs_graphics_colour_integral_standard_colours();
void test_rs_graphics_colour_integral_arithmetic();
void test_rs_graphics_colour_concepts();
void test_rs_graphics_colour_channel_order();
void test_rs_graphics_colour_premultiplied_alpha();
void test_rs_graphics_colour_alpha_blending();
void test_rs_graphics_colour_conversion_between_colour_spaces();
void test_rs_graphics_colour_conversion_between_representations();
void test_rs_graphics_colour_interpolation();
void test_rs_graphics_colour_hex_representation();
void test_rs_graphics_geometry_box();
void test_rs_graphics_geometry_sphere();
void test_rs_graphics_image_construction();
void test_rs_graphics_image_pixel_access();
void test_rs_graphics_image_premultiplied_alpha();
void test_rs_graphics_image_conversion();
void test_rs_graphics_noise_result_stability();
void test_rs_graphics_noise_multiple_sources();
void test_rs_graphics_noise_statistics();
void test_rs_graphics_noise_sample_renders();
void test_rs_graphics_root_finding_newton_raphson_float();
void test_rs_graphics_root_finding_newton_raphson_double();
void test_rs_graphics_projection_polar_coordinate_normalisation();
void test_rs_graphics_projection_azimuthal_equidistant();
void test_rs_graphics_projection_gnomonic();
void test_rs_graphics_projection_lambert_azimuthal();
void test_rs_graphics_projection_orthographic();
void test_rs_graphics_projection_stereographic();
void test_rs_graphics_projection_cylindrical_equidistant();
void test_rs_graphics_projection_gall_peters();
void test_rs_graphics_projection_lambert_cylindrical();
void test_rs_graphics_projection_mercator();
void test_rs_graphics_projection_eckert_iv();
void test_rs_graphics_projection_mollweide();
void test_rs_graphics_projection_sinusoidal();
void test_rs_graphics_projection_interrupted_eckert_iv();
void test_rs_graphics_projection_interrupted_mollweide();
void test_rs_graphics_projection_interrupted_sinusoidal();
void test_rs_graphics_projection_sample_maps();
void test_rs_graphics_version();

int main(int argc, char** argv) {

    main_args = std::vector<std::string>(argv + 1, argv + argc);
    std::println("");
    std::println("{}Running unit tests{}", xhead, xreset);
    std::println("{}{}{}", xrule, rule, xreset);

    call_me_maybe(test_rs_graphics_colour_space_concepts, "test_rs_graphics_colour_space_concepts");
    call_me_maybe(test_rs_graphics_colour_space_ciexyy, "test_rs_graphics_colour_space_ciexyy");
    call_me_maybe(test_rs_graphics_colour_space_cielab, "test_rs_graphics_colour_space_cielab");
    call_me_maybe(test_rs_graphics_colour_space_cieluv, "test_rs_graphics_colour_space_cieluv");
    call_me_maybe(test_rs_graphics_colour_space_hclab, "test_rs_graphics_colour_space_hclab");
    call_me_maybe(test_rs_graphics_colour_space_hcluv, "test_rs_graphics_colour_space_hcluv");
    call_me_maybe(test_rs_graphics_colour_space_srgb, "test_rs_graphics_colour_space_srgb");
    call_me_maybe(test_rs_graphics_colour_space_adobe_rgb, "test_rs_graphics_colour_space_adobe_rgb");
    call_me_maybe(test_rs_graphics_colour_space_pro_photo, "test_rs_graphics_colour_space_pro_photo");
    call_me_maybe(test_rs_graphics_colour_space_wide_gamut, "test_rs_graphics_colour_space_wide_gamut");
    call_me_maybe(test_rs_graphics_colour_space_hsl, "test_rs_graphics_colour_space_hsl");
    call_me_maybe(test_rs_graphics_colour_space_hsv, "test_rs_graphics_colour_space_hsv");
    call_me_maybe(test_rs_graphics_colour_space_greyscale, "test_rs_graphics_colour_space_greyscale");
    call_me_maybe(test_rs_graphics_colour_space_sgreyscale, "test_rs_graphics_colour_space_sgreyscale");
    call_me_maybe(test_rs_graphics_colour_space_conversion, "test_rs_graphics_colour_space_conversion");
    call_me_maybe(test_rs_graphics_colour_floating_point_elements, "test_rs_graphics_colour_floating_point_elements");
    call_me_maybe(test_rs_graphics_colour_floating_point_arithmetic, "test_rs_graphics_colour_floating_point_arithmetic");
    call_me_maybe(test_rs_graphics_colour_floating_point_standard_colours, "test_rs_graphics_colour_floating_point_standard_colours");
    call_me_maybe(test_rs_graphics_colour_integral_elements, "test_rs_graphics_colour_integral_elements");
    call_me_maybe(test_rs_graphics_colour_integral_standard_colours, "test_rs_graphics_colour_integral_standard_colours");
    call_me_maybe(test_rs_graphics_colour_integral_arithmetic, "test_rs_graphics_colour_integral_arithmetic");
    call_me_maybe(test_rs_graphics_colour_concepts, "test_rs_graphics_colour_concepts");
    call_me_maybe(test_rs_graphics_colour_channel_order, "test_rs_graphics_colour_channel_order");
    call_me_maybe(test_rs_graphics_colour_premultiplied_alpha, "test_rs_graphics_colour_premultiplied_alpha");
    call_me_maybe(test_rs_graphics_colour_alpha_blending, "test_rs_graphics_colour_alpha_blending");
    call_me_maybe(test_rs_graphics_colour_conversion_between_colour_spaces, "test_rs_graphics_colour_conversion_between_colour_spaces");
    call_me_maybe(test_rs_graphics_colour_conversion_between_representations, "test_rs_graphics_colour_conversion_between_representations");
    call_me_maybe(test_rs_graphics_colour_interpolation, "test_rs_graphics_colour_interpolation");
    call_me_maybe(test_rs_graphics_colour_hex_representation, "test_rs_graphics_colour_hex_representation");
    call_me_maybe(test_rs_graphics_geometry_box, "test_rs_graphics_geometry_box");
    call_me_maybe(test_rs_graphics_geometry_sphere, "test_rs_graphics_geometry_sphere");
    call_me_maybe(test_rs_graphics_image_construction, "test_rs_graphics_image_construction");
    call_me_maybe(test_rs_graphics_image_pixel_access, "test_rs_graphics_image_pixel_access");
    call_me_maybe(test_rs_graphics_image_premultiplied_alpha, "test_rs_graphics_image_premultiplied_alpha");
    call_me_maybe(test_rs_graphics_image_conversion, "test_rs_graphics_image_conversion");
    call_me_maybe(test_rs_graphics_noise_result_stability, "test_rs_graphics_noise_result_stability");
    call_me_maybe(test_rs_graphics_noise_multiple_sources, "test_rs_graphics_noise_multiple_sources");
    call_me_maybe(test_rs_graphics_noise_statistics, "test_rs_graphics_noise_statistics");
    call_me_maybe(test_rs_graphics_noise_sample_renders, "test_rs_graphics_noise_sample_renders");
    call_me_maybe(test_rs_graphics_root_finding_newton_raphson_float, "test_rs_graphics_root_finding_newton_raphson_float");
    call_me_maybe(test_rs_graphics_root_finding_newton_raphson_double, "test_rs_graphics_root_finding_newton_raphson_double");
    call_me_maybe(test_rs_graphics_projection_polar_coordinate_normalisation, "test_rs_graphics_projection_polar_coordinate_normalisation");
    call_me_maybe(test_rs_graphics_projection_azimuthal_equidistant, "test_rs_graphics_projection_azimuthal_equidistant");
    call_me_maybe(test_rs_graphics_projection_gnomonic, "test_rs_graphics_projection_gnomonic");
    call_me_maybe(test_rs_graphics_projection_lambert_azimuthal, "test_rs_graphics_projection_lambert_azimuthal");
    call_me_maybe(test_rs_graphics_projection_orthographic, "test_rs_graphics_projection_orthographic");
    call_me_maybe(test_rs_graphics_projection_stereographic, "test_rs_graphics_projection_stereographic");
    call_me_maybe(test_rs_graphics_projection_cylindrical_equidistant, "test_rs_graphics_projection_cylindrical_equidistant");
    call_me_maybe(test_rs_graphics_projection_gall_peters, "test_rs_graphics_projection_gall_peters");
    call_me_maybe(test_rs_graphics_projection_lambert_cylindrical, "test_rs_graphics_projection_lambert_cylindrical");
    call_me_maybe(test_rs_graphics_projection_mercator, "test_rs_graphics_projection_mercator");
    call_me_maybe(test_rs_graphics_projection_eckert_iv, "test_rs_graphics_projection_eckert_iv");
    call_me_maybe(test_rs_graphics_projection_mollweide, "test_rs_graphics_projection_mollweide");
    call_me_maybe(test_rs_graphics_projection_sinusoidal, "test_rs_graphics_projection_sinusoidal");
    call_me_maybe(test_rs_graphics_projection_interrupted_eckert_iv, "test_rs_graphics_projection_interrupted_eckert_iv");
    call_me_maybe(test_rs_graphics_projection_interrupted_mollweide, "test_rs_graphics_projection_interrupted_mollweide");
    call_me_maybe(test_rs_graphics_projection_interrupted_sinusoidal, "test_rs_graphics_projection_interrupted_sinusoidal");
    call_me_maybe(test_rs_graphics_projection_sample_maps, "test_rs_graphics_projection_sample_maps");
    call_me_maybe(test_rs_graphics_version, "test_rs_graphics_version");

    std::println("{}{}{}", xrule, rule, xreset);

    if (failures == 0) {
        std::println("{}OK - all tests passed{}", xpass, xreset);
    } else {
        std::println("{}*** Test failures: {}{}", xfail, failures, xreset);
    }

    std::println("");

    return failures;

}
