// This file is generated by the bump-version script

#pragma once

#include <array>
#include <string>

namespace RS::Graphics {

    inline std::array<int, 3> version() noexcept {
        return {{ 0, 1, 3 }};
    }

    inline std::string version_string() {
        return "0.1.3";
    }

}
